on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  list-h:
    runs-on: ubuntu-latest
    outputs:
      list: ${{ steps.list.outputs.list }}
    steps:
    - run: clang++ --version
    - uses: actions/checkout@main
      with:
        ref: ${{ github.ref }}
    - run: ls -l .github/workflows/main.m4.cc
    - id: list
      run: |
        find include/. -type f -name '*.h' -o -type f -name '*.hh' \
        | python3 -c "
        import sys,json
        print(json.dumps({'h':list(map(lambda h:h.strip() , sys.stdin.readlines()))}))" \
        | xargs -0 -I% echo 'list=%' | tee --append "$GITHUB_OUTPUT"
  independence-check:
    runs-on: ubuntu-latest
    needs: list-h
    #if: ${{ needs.list-h.outputs.list != '[]' && needs.list-h.outputs.list != '{}' && needs.list-h.outputs.list != '' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.list-h.outputs.list) }}
    steps:
    - uses: actions/checkout@main
      with:
        ref: ${{ github.ref }}
    - run: |
        m4 -D__h__="${{ matrix.h }}" .github/workflows/main.m4.cc | tee /dev/stderr | clang++ -x c++ - ; stat a.out >/dev/null && rm a.out
