on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  clang-exists:
    runs-on: ubuntu-latest
    steps:
    - run: clang --version
  list-h:
    runs-on: ubuntu-latest
    needs: clang-exists
    outputs:
      fils: ${{ steps.list.outputs.list }}
    steps:
    - uses: actions/checkout@main
      with:
        ref: ${{ github.ref }}
    - run: ls -l .github/workflows/main.m4.cc
    - id: list
      run: |
        find include/. -type f -name '*.h' -o -type f -name '*.hh' | python3 -c "import sys,json ; print(json.do=umps({'h':sys.stdin.readlines()}))" | xargs -0 -I% echo 'list=%' | tee -append "$GITHUB_OUTPUT"
  independence-check:
    runs-on: ubuntu-latest
    needs: list-h
    if: ${{ needs.list-h.outputs.list != '[] && needs.list-h.outputs.list != '{}' && needs.list-h.outputs.list != '' }}
    strategy:
      matrix: ${{ fromJson(needs.list-h.outputs.list) }}
    steps:
    - uses: actions/checkout@main
      with:
        ref: ${{ github.ref }}
    run: ls ${{ matrix.h }}
